version: '3.4'

services:
  db:
    image: postgres:12
    restart: always
    container_name: sc-db
    environment:
      POSTGRES_USER: spacecartels
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: spacecartels
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
  store:
    image: redis:6
    restart: always
    container_name: sc-store
    ports:
      - '6379:6379'